import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: 'Amazon Web Service(AWS)',
      position: 'Technical Account Manager, ',
      startedAt: '2022-12',
      descriptions: [
        {
          projectName: 'Samsung Gaming Hub(MX)',
          projectDetail: [
            'Samsung galaxy game launcher/hub system maintenance and support',
            'Monitored and analyzed cloud performance metrics, identifying and resolving issues before they impacted end-users',
            'Managed the day-to-day tactical and long term strategic activities and projects with the customer',
          ],
        },
        {
          projectName: 'Samsung Big Data Center(DX)',
          projectDetail: [
            'Samsung galaxy user log data collecting and analyzing system pipelines(30PB-Petabytes) maintenance and support',
            'Samsung galaxy user device log data lake system(Big Data Platform), establishment of an enterprise-wide customer integration DB maintenance and support',
            'Developed and maintained disaster recovery plans for cloud-based applications, ensuring business continuity in the event of a system outage',
          ],
        },
        {
          projectName: 'Samsung Research(SR)',
          projectDetail: [
            'Data Catalog Service data warehouse and analyzing system support(4PB, 42000 RPS, DR architecture, Lambda to ECS Conversion)',
            'Generative AI HPC for multi GPU training(NCCL, RDMA Infiniband cluster) architecture design and documentation of technical environments support',
            'Samsung Bixby A Large Language Model(LLM) trainning infra architecture design and POC project support',
            'Troubleshot and resolved complex cloud-related issues, resulting in a 10% reduction in system downtime and improved end-user satisfaction.',
            'Assist customers with identifying model drift and retraining models',
            'Work with our Professional Services DevOps consultants to help our customers operationalize models after they are built.',
          ],
        },
        {
          projectName: 'Samsung Digital Appliance(DA)',
          projectDetail: [
            'Collaborated with the security team to develop and implement cloud security policies, resulting in a 10% reduction in security incidents and improved compliance with industry regulations',
            'Recommended and implemented new cloud technologies, resulting in a 10% reduction in operational costs and improved scalability for future growth.',
            'Lead the definition, design, and documentation of technical environments',
          ],
        },
        {
          projectName: 'ETC',
          projectDetail: [
            '<a target="_blank" href="https://coral-macaroni-54f.notion.site/2024-06-AWS-50b225b640a54617990eb6bc7aefdb00">AWS 삼성전자 세미나-Sagemaker FineTuning with Experiments</a>',
            '<a target="_blank" href="https://github.com/son-kjun/bedrock-workshop">AWS 생성형AI 워크샵을 위한 HandOnLab</a>',
            'Developing AWS Samsung billing summary and statistics monitoring tool with python.',
            'Presented AI/ML tech session for AWS(ES internal)',
            'Presented Gen AI/ML(Sagemaker, ModelServing, MLOps) For Customers(external)',
            'AWS 비용 최적화 및 서비스 복잡성 감소 아키텍처 설계 지원',
            'AWS 서비스 중단, 서비스 지표, 서비스 출시 전 계획 검토 수행',
            'AWS 서비스 운영 퍼포먼스 분석 및 주기적 운영 상황 결과 리포트 제공',
            '사고/장애, DR 설계 지원, 트레이드 오프 및 리스크 관리, 리더십팀과 기술적 논의 주도',
            'AWS 글로벌 서비스 팀 협력 후 고객 이슈 해결',
            'AWS Architecture(EC2, RDS, DynamoDB, S3 등) 최적화 지원',
          ],
        },
      ],
      skillKeywords: [
        'AWS GenAI',
        'AWS Security',
        'AWS Infra',
        'Cloud cost optimization',
        'Multi GPU Cluster Infra',
        'Cross-functional collaboration',
        'IaC',
        'Accelerated computing',
        'LLM',
        'NLP',
        'NVidia NCCL',
        'BigData',
        'AI/ML',
        'MLOps',
        'DevOps',
      ],
    },
    {
      title: '(주)KB국민은행',
      position: 'AI금융센터(과장)',
      startedAt: '2019-12',
      endedAt: '2022-11',
      descriptions: [
        {
          projectName: 'KB 전 계열사 인공지능 금융AI비서(AICC) MLOps 프로젝트 참여',
          projectDetail: [
            'AWS, Python Ray Serve, BentoML, GitOps, ArgoCD, Istio, CI/CD, Airflow, Grafana, Prometheus 등',
            'AWS 서비스 메시 아키텍처 설계(EKS, Istio 기반) 및 적용, 서비스 수준 제어, 통신 장애, 트래픽 모니터링/제어',
            '딥러닝 모델 서빙, 모델 변경 관리/배포(레포지토리, 모델 버전) 구축, 모델 컴파일/성능/신뢰도/정확도 측정',
            '모델 서빙 프레임워크 안정성 비교 및 인퍼런스 최적화 테스트, 서빙 성능 극대화 작업(Performance Analyzer)',
            'KB금융 자체 자연어 처리 플랫폼(KB-STA) 모델 경량화 지원(개체명 인식, 형태소 분석, 인텐트 분류기)',
            '금융AI비서(AICC) 구축 요건 정의서(AI 챗봇 영역)작성 및 평가 항목 작성, 업체 선정 심사 참여/확정',
            '컨테이너 기반 콜봇 서비스 모델 서빙 아키텍처 설계 및 프로토 타입 개발',
            '<a target="_blank" href="https://www.newstomato.com/readNewspaper.aspx?no=1126892">은행원 대신 가상인간" 국민은행의 AI금융비서 실험</a>',
            '<a target="_blank" href="https://www.etnews.com/20240306000220">“내 손안의 금융비서” KB국민은행, 모바일 특화 AI 고도화</a>',
            '<a target="_blank" href="https://www.g-enews.com/article/Finance/2020/06/20200618141958190da878e5c53_1">KB국민은행, 한글 자연어 학습 모델 KB ALBERT 개발</a>',
          ],
        },
        {
          projectName: 'KB 전 계열사 인공지능 AI 상담콜봇(Callbot) 도입 및 구축 지원 업무(TF팀)',
          projectDetail: [
            '스타트업/기업별 챗봇 데모 기반 제품 정확도 측정 및 성능 평가, 기술 협력 가능 검토',
            '사업 계획 및 제안 검토/평가 및 업체 선정 참여(AI/ML 사업 영역 평가 기준 수립)',
            'AICC 사업 구축 가능 업체(빅테크, 중견기업) 협의 및 하이브리드(망분리) 클라우드 아키텍처 적용 기술 검토',
            'AI상담 콜봇 구축요건정의서(RFP) 작성 및 4대 검토(아키텍처, 정보보안, 용량산정, 이중화, 재해복구 등) 지원',
            '생성 AI기술 협약 스타트업 서칭 및 기반 기술 이전 및 자체 개발 시스템 계획 수립',
            '<a target="_blank" href="http://kpenews.com/View.aspx?No=2527370">AI은행원 고객 접점 늘린다..KB국민은행, 콜봇 서비스 ‘똑똑’ 전진 배치</a>',
            '<a target="_blank" href="https://www.globalnewsagency.kr/news/articleView.html?idxno=270125">KB국민은행, 고령층 고객을 위한 ‘콜봇 서비스’ 지원</a>',
          ],
        },
        {
          projectName: 'KB국민은행 메타버스(Metaverse) 금융연계 시스템 테스트 베드 기획 및 개발',
          projectDetail: [
            'Development Lead & Managing',
            'Aws, Lambda, Python Ray, Kubernetes, Docker, GameAnalytics, Lua, MongoDB, CI/CD',
            '메타버스 플랫폼 기반 뱅킹 연계 시나리오 기획, 작성 및 관련 보안성 심의, 금융 감독 규정 대응 보고서 작성',
            '유저 로그 분석 저장 시스템 백엔드(백로그, 접속, 액션, 중요도 분류, 캐릭터 이벤트 발생 실시간 로그 저장) 개발',
            '유저 로그 데이터 시각화 대시보드(유저 인입률, 유저 스테이터스, 게임 전체 이벤트 활용률 등) 화면 개발',
            '<a target="_blank" href="https://biz.chosun.com/stock/finance/2022/02/09/NINCMSR4JJGI7LNMUDKYQBPN6I">KB국민은행, 로블록스(Roblox)로 ‘메타버스 금융’ 시도</a>',
            '<a target="_blank" href="https://www.econovill.com/news/articleView.html?idxno=542825">KB국민은행, 메타버스·디지털자산·금융 접점 찾는다</a>',
            '<a target="_blank" href="https://www.kbanker.co.kr/news/articleView.html?idxno=200455">KB의 새 메타버스 실험…“현장감 살린 영업점포 구현 중”</a>',
          ],
        },
        {
          projectName: '무설치 웹 브라우저 기반 화상회의 시스템 개발',
          projectDetail: [
            'Development Lead & Managing',
            'Aws, Chime, Docker, TypeScript, Webrtc, Socket.IO, Tensor.js BodyPix, Kubernetes',
            'MSCOCO Person, PFCN, AISegment(BodyPix) 데이터 기반 실시간 백그라운드 화면 제거 기능 추가',
            '무설치 브라우저 기반 원클릭 리모트 화상회의 시스템 프로젝트 POC 개발',
            'CI/CD(Code Deploy, Jenkins), Kubernetes 메트릭(Grafana-Prometheus), 로그(EFK 스택) 구축',
            '그룹 임직원 테스트 좋은 피드백, 기술 내재화, 영업점 적용 및 고도화 적용 보고서 작성',
            '<a target="_blank" href="https://www.youthdaily.co.kr/mobile/article.html?no=120894">"어디서든 비대면으로" KB국민은행 "모바일 화상상담 서비스" 확대</a>',
          ],
        },
        {
          projectName: 'Antoc(앤톡) 기업 여신 가치 평가 크롤링 시스템 POC 개발',
          projectDetail: [
            'Python, SpringBoot, Oracle12c, Bootstrap, Android',
            '기업 여신 대출 평가 기준 기업 정보(기업정보, 신용정보, 기술정보, 특허 등) 데이터 수집 크롤링 모듈 개발',
            '기업 정보 데이터 일정 주기 저장, 업데이트 배치 스크립트 개발 및 Rest API 서버 개발',
            '영업점 여신 대출 담당 기업 심사 프로세스 자동화 및 운영 조직 부담 감소, 향후 차세대 프로젝트 적용 요청',
          ],
        },
        {
          projectName: '모바일 브랜치 웹 뱅킹 개발 협업',
          projectDetail: [
            'Spring, WebRTC Image Capture, OCR 등',
            'IB프레임워크 기반 대고객 인터넷 뱅킹 비대면 계좌 발급 시스템 구축(KB국민은행 예금/적금)',
            '계정계 고객 확인 의무, 자금세탁방지 CDD/EDD 처리 개발 협업',
            '주민등록증 발급 일자, 안면 사진 인식 OCR 기능 연동 모듈 개발, BMT 테스트 지원 및 서비스 안정화',
            '은행 고유 업무 수신/상품 파트 개발 투입 및 도메인 지식 습득',
            '모놀로지 코어뱅킹(단일코드) 기반 대용량 트래픽 아키텍처 변화 설계(동시성, 비동기) 지원',
            '<a target="_blank" href="https://www.hankyung.com/article/2020091463216">앱·인증서 없어도 OK! KB국민은행, "모바일브랜치" 출시</a>',
            '<a target="_blank" href="https://m.joseilbo.com/news/view.htm?newsid=437905#_enliple">KB국민은행, "KB모바일 브랜치" 신규 가입 이벤트 진행</a>',
            '<a target="_blank" href="https://www.fntimes.com/html/view.php?ud=202009141115486803179ad43907_18">국민은행, 웹기반 "KB모바일브랜치" 출시…공인인증서 없이 상품가입</a>',
          ],
        },
        {
          projectName: 'KB MyStar 상담 내역 분석',
          projectDetail: [
            'Konlpy, Mecab, Tensorflow, Plotly Dash',
            'KB 금융 상담 만족도 평가 자동화 시스템 구축 목표 사전 POC',
            '고객만족도 식별 및 마케팅 계획 수립을 위한 핵심 학습 데이터 레이블링 작업',
            'KB 전체 영업점 과거 10년 수기 상담내역 텍스트 데이터 분석(긍정 ,부정, 고객 이탈 방지 키워드 등)',
            '영업점 방문자 업무 처리 결과 만족도 유형화, 동향, 추세 결과 대시보드 시각화 및 보고서 제출',
          ],
        },
        {
          projectName: '디지털 인감 유사도 분석(Image Comparison)',
          projectDetail: [
            'OpenCV 2.4.4 SSIM, SIFT, SURF, ORB 알고리즘 활용 이미지 매칭 비교 분석',
            'Comparative Analysis of CNN-based Model for image Similarity Measurement',
            '영업정 인감 도장(이미지) 특성(각도, 마모도, 농도)맞는 학습 데이터 생성',
            'KB 전체 영업점 개인 및 기업 고객 인감 이미지 자동, 매칭 시스템 POC 개발',
            '유관부서 및 관련 기술 업체 협업 및 사업 전략 수립, POC 최종 결과 이미지 비교 정확도 88% 향상',
          ],
        },
        {
          projectName: '신용카드 카드 전표 OCR 처리 판독 정확도 향상 POC 프로젝트',
          projectDetail: [
            'Tesseract-OCR, Custom tesseract training tools',
            'KB 국민은행 전체 영업점 신용 카드 전표 수기 입력 자동화 목표 OCR 인식 개선',
            '필체 인식 정확도 상승 목표 학습 데이터 Box 생성, 이미지 전처리 및 LSTM 파리미터 튜닝 모델 학습',
            '전국 영업점 신용카드 매출 전표 발생량 집계 데이터 시스템 연동 방향성 수립 및 설계 보고서 도출',
          ],
        },
        {
          projectName: '전자필경대 시스템 POC 개발(대기 고객 사전 서류 작성)',
          projectDetail: [
            'HTML5 Canvas, Node.js',
            '고객 정보/서명(Sign) 입력, 암호화 및 저장 파트 개발',
            'KB 국민은행 전체 영업점 고객 대기 시간 및 혼잡도 감소 위한 사전 서류 작성 시스템 POC 개발',
            '기존 번호표 발급 시스템 연동 및 태블릿 기반 고객 정보 입력 및 사전 대기 시스템 시험 개발 및 테스트',
            '<a target="_blank" href="https://www.babytimes.co.kr/news/articleView.html?idxno=41541">KB국민은행, "미리작성 서비스"로 고객 대기시간 단축</a>',
          ],
        },
      ],
      skillKeywords: [
        'MLOps',
        'DevOps',
        'NLP',
        'AWS',
        'Tensorflow',
        'Docker',
        'AI/ML',
        'BentoML',
        'ONNX',
        'Airflow',
        'EFK',
        '프로젝트관리',
        '사업관리',
        '보고서 작성',
        '수신업무',
        '신기술 발굴',
        '비대면 금융 서비스 백엔드',
        'ChatBot',
        'OpenCV',
        'WebRTC',
        'Android',
      ],
    },
    {
      title: '(주)NHN다이퀘스트',
      position: '과장(프리랜서)-TA사업부',
      startedAt: '2018-09',
      endedAt: '2019-05',
      descriptions: [
        {
          projectName: 'LG 유플러스 AICC 실시간 상담 어드바이저 POC 구축',
          projectDetail: [
            'LG 유플러스 고객 실시간 상담 통화 만족도 측정 알고리즘 개발',
            '실시간 채팅 상담 스크립트 어드바이저 및 자동 평가 시스템 POC 개발',
            'Web Socket 기반 채팅 상담 시스템(30채널) 및 MongoDB 기반 채팅 메시지 저장소 설계',
            '상담사 별 실시간 채팅 모니터링 및 전체 현황 대시보드(통화/대기 상담원, 만족도, 통계, 인입) 기능 화면 설계',
            '통화 종료 데이터 문장 전처리(간투어, 불용어 제거 등) 및 콜 단위 전문 데이터 생성 작업',
            '학습 추론 모델(상담 유형 분류 및 추천어, 상담 도움말 제공) 서빙 API 개발',
            '콜센터 일일 전체 상담 학습 데이터 전처리, 추론 모델 재 학습 배치 스크립트 개발',
            '<b>성과 : 정규직 대상 아키텍처/솔루션 지식 교육, 다수 기업, LG 유플러스 AICC 프로젝트 수주에 영향력 발휘</b>',
          ],
        },
        {
          projectName: '주)한국장학재단 IVR 고도화 및 VOC 분석 시스템 구축',
          projectDetail: [
            'Development Lead',
            '과거/현재 실시간 상담 문장 데이터 저장 데이터 레이크 구성 및 파이프라인 구축 스크립트 개발 담당',
            'Sqoop 기반 MariaDB -> HDFS 변환 및 HiveSQL 조회 기능 개발',
            '어휘 분석, 개체명 인식(Tagging) 작업, 문장 분리, 토크나이징, 품사 변환 및 상담사 추천 스크립트 추출 개발',
            '모델 재학습 배치 스크립트 개발 및 학습 모델 버전 관리 레포지토리 구축',
            '하둡 네임노드 및 데이터 노드, 데이터 레플리카 구성, 장애시 가용성 대비, 실제 장애 복원 테스트 수행',
            '<b>성과 : AICC, STT/TA 사업 확장 발판 마련 및 금융권 계약 수주, 설치형 서비스 기반 구축</b>',
          ],
        },
        {
          projectName: '(주)롯데정보통신 ML 기반 AICC 솔루션 구축 프로젝트',
          projectDetail: [
            'Development Lead',
            '롯데 계열사(롯데마트, 롯데 면세점, 롯데리아) 고객 상담사 대상 STT/TA 프로젝트 개발 리드',
            'STT 변환 상담 문장 데이터 DB 실시간 이중화(Replication) 저장 및 Master, Slave 구성',
            '과거 5분 상담콜 문장 데이터 기본 베이스 상담 내역/자동 요약/상담 유형 분류/키워드 추출 작업 파트 개발',
            '유사도 분석, 묵음 구간 분석, 고객불만 지수 그룹핑, 감정분석, 핵심어 추출 제공 Rest API 개발',
            '전체 상담사 현황 대시보드 전광판(통화/대기 상담원, 부서, 만족도, 통계) 대시보드 화면 차트 개발',
            'RNN 알고리즘 기반 재학습 모델 버전 동기화 배치 스케쥴러 개발 및 정확도 테스트 자동화 작업',
            '<b>성과 : 롯데 계열사 STT/TA 구축 후 LG, 한화, 금융권 등 다수 기업 TA 시스템 도입 및 계약 성사</b>',
            '<a target="_blank" href="https://www.ezyeconomy.com/news/articleView.html?idxno=126963">롯데정보통신, 고객센터 전문 AI 상담 서비스 론칭</a>',
          ],
        },
      ],
      skillKeywords: [
        'Python',
        'Java',
        'AWS',
        'AICC',
        'STT/TTS',
        'Konlpy',
        'FastAPI',
        'AI/ML',
        'Model Serving',
        'Django',
        'Flask',
        'Keras',
        'SpringBoot',
        'Redis',
        'NLP',
        'Hadoop',
        'Spark',
        'MariaDB',
      ],
    },
    {
      title: '(주)디오팩토리',
      position: '과장 (개발연구소)',
      startedAt: '2016-12',
      endedAt: '2018-08',
      descriptions: [
        {
          projectName: '신한은행 희망 위기재정 프로젝트 사이트 개발',
          projectDetail: [
            '신용 위기 재정 대상자 대출 심사 백엔드 예약 시스템 설계 및 구축 런칭',
            '대규모 인입 트래픽 수요 예측 대비 Nginx, Tomcat 세션클러스터링, 로드밸런싱 설정 구성',
            '기존 비효율적 비즈니스 로직 개선 후 트래픽 N% 감소',
            '위기재정 대상자 필수 정보 통합 검색 서비스 화면 개발',
            'DB -> 암호화 파일 저장 및 FTP 전송 파트 개발',
          ],
        },
        {
          projectName: '행정자치부 국민포럼 정부혁신 사이트 데이터 레이크 구축',
          projectDetail: [
            '현 행정자치부 국민 포럼 10년 간 대용량 데이터(5TB) 전처리 및 마이그레이션 작업',
            '스키마 컨버전 및 마이그레이션 다운타임 최소화 및 롤백 쉘 스크립트 작성',
            'Nginx + Tomcat 세션 클러스터링 및 로드밸런서 설정, 무중단 배포 구성',
            'Sqoop 기반 RDBMS -> HDFS 마이그레이션 작업 및 하둡 Reducer 작업 최적화',
            '정형/비정형 데이터 분산 저장 처리(클러스터) 설정 작업 및 실시간 인기 검색어 조회 시스템 추가 개발',
          ],
        },
        {
          projectName: '㈜현대자동차 안드로이드 블루투스 기반 Smart Key Band 개발',
          projectDetail: [
            '해외 현대자동차 구매자 대상 안드로이드 스마트 밴드 전용 Native 앱 개발',
            '차량 운행 정보, 건강(심박)정보, 이동거리 정보 등 센서 데이터 실시간 수집 후 스마트폰 전송 개발',
            '사용자 정보 발생 이벤트 핸들링 및 데이터 실시간 통합 후 전송 Rest API 서버 구축',
            '차량 및 스마트밴드 블루투스 통신 동기화 및 휴대폰 기종 별 블루투스 모듈 버전 호환성 문제 해결',
            'API 모니터링, 사용자 헬스 정보 대시보드 구성 및 개발',
          ],
        },
        {
          projectName: '경기도 이천 시청 애니메이션 박람회 사이트 구축',
          projectDetail: [
            'Development Project Management',
            '박람회 정보 및 예약서비스 제공 서비스 데이터 모델링 및 API 개발',
            '설계 분석 후 고객 요건 사항 정리 및 사이트 구조 설계, 기획서 분석',
          ],
        },
        {
          projectName: 'NCS기반 경민대학교, 백제대학교 학사 운영/관리 개발 시스템',
          projectDetail: [
            '학생 및 교수 상담 예약 시스템 구축 및 상담 결과 PDF 변환 파트 개발',
            'Storybook 활용 시각적 테스팅과 API 명세 문서를 관리 주도 개발',
            '크로스 브라우징 이슈 체크 및 수정, 웹표준, 웹 접근성 개선 작업',
          ],
        },
        {
          projectName: '행정자치부 대표 모바일용 홈페이지 성능 개선 사업',
          projectDetail: [
            'Legacy 소스코드 리팩토링 및 비즈니스 로직 변경',
            '서버 퍼포먼스(부하, 지속성, 스트레스, 스파이크, 중단점) 테스트 수행',
            'JMeter, nGrinder 도구 사용 TPS(결과트리, HTML)/프로젝트 종료 보고서 작성',
          ],
        },
      ],
      skillKeywords: [
        'Java',
        'Spring',
        'MySQL',
        'Hadoop',
        'Sqoop',
        'Tibero',
        'React',
        'Android',
        'Retrofit',
        'Bluetooth',
        'Javascript',
        'Angular',
        'Vue',
        'JMeter',
        'nGrinder',
      ],
    },
    {
      title: '(주)아이온커뮤니케이션즈',
      position: '선임연구원(ECM개발팀)',
      startedAt: '2015-04',
      endedAt: '2016-06',
      descriptions: [
        {
          projectName: 'e-Form 온라인 전자 계약 서비스 고도화 및 운영',
          projectDetail: [
            '전자 계약서 온라인 기반 작성, 계약 체결, 필드 매핑 관리, 전송 프로세스 설계 및 구축',
            '주기적으로 변경 및 강화되는 전자문서 계약 및 효력 정책을 프로젝트에 적용',
            '계약서 스캔 이미지 OCR 모듈 파라미터 조절 한/영 인식 정확도 상승 작업',
            '계약서 종류(전자양식) 자동 분류 인터페이스 Rest API 파트 개발 ',
            'ElarsticSearch 클러스터 구축 및 검색 Query 튜닝, 노드간 불룜 사용량 불균형 문제 해결',
            '<b>성과 : 비대면 온라인 계약 시스템 최초 구축 및 다수 대기업 계약 체결, 대용량 트래픽 처리 및 운영 노하우 경험</b>',
          ],
        },
        {
          projectName: 'iDrive EDMS 개발 및 운영',
          projectDetail: [
            '전자문서 관리 시스템(EDMS) 구축 및 개선, 전자 문서 생성 및 결제, 폐기 시스템 운영 업무',
            'OCR 기반 자동 문서 분류 시스템(한글/영문, 계약서 등) 구축 및 커스터마이징 파트 담당',
            '다양한 한글 폰트에 따른 문자 인식 정확도 상승을 위한 커스터마이징',
            '기타 메뉴 구조 설계 및 소스코드 최적화 및 성능 개선 작업 참여',
            '클라우드 기반 서비스 사내 최초 도입 참여, SaaS 형태의 해외 서비스 제공 ',
            '<b>성과 : AWS 기반 대용량 트래픽 처리 및 비용 절감, 자연어 기반 개체명 인식기 구축 기술 습득, 해외 계약 성사</b>',
          ],
        },
        {
          projectName: 'POSCO ICT 스마트그리드 수요관리 예측 시스템 구축 및 운영',
          projectDetail: [
            '전력 소비자 및 생산자 양방향 실시간 데이터 공유 및 에너지 효율성 지표 대시보드 개발',
            '전력 에너지 효율적 사용을 위한 에너지 소비 패턴 및 지능적 전력량 사용 예측 시스템 구축',
            '기간, 계절별 전력 수요 예측 및 실시간 사용량 데이터 저장 위한 Elarsticsearch 노드, 샤드, 클러스터링 작업',
            '생산성/경제성 이론 기반 차트 실시간 시각화 작업 및 외부 Rest API 서버 개발',
            'Elarsticsearch Read Replica 활용 명령 요청 분산 모듈 구현',
            '<b>성과 : 대규모 서비스 트래픽 처리 및 시각화 및 운영 노하우 경험, 향후 스마트 그리드 해외 진출 및 국내 수주 발판</b>',
          ],
        },
      ],
      skillKeywords: [
        'Java',
        'Spring',
        'ElasticSearch',
        'Python',
        'OCR',
        'AWS',
        'BootStrap',
        'RabbitMQ',
      ],
    },
    {
      title: '(주)넥서스웨어',
      position: '과장 (SI사업수행팀)',
      startedAt: '2013-04',
      endedAt: '2015-03',
      descriptions: [
        {
          projectName: '일반적 SI 파견 및 웹 서비스 개발 및 프로젝트 매니징 업무',
          projectDetail: [],
        },
        {
          projectName: 'LG 유플러스 유플릭스 무비 하이브리드 앱 고도화 프로젝트',
          projectDetail: [
            'Development Project Lead',
            '기존 코르도바 기반 하이브리드 앱 코드 개선',
            'CD/CI 파이프라인 구축 및 Rebbit MQ, Jenkins 설정',
            'Spring EnCache 활용 필수 리딩 데이터 부하(트래픽) 감소 및 확장성 개선',
          ],
        },
        {
          projectName: 'KT텔레캅 현행 시스템 기능 개선 및 고도화 작업',
          projectDetail: [
            '스프링/마이플랫폼 기반 ERP 기능 추가 및 소스코드 개선 후 성능 최적화 작업',
            '관제 서비스에 사용되는 API 서버 개발',
            '비즈니스 회의를 통한 개발 확장성/모듈화 장점 제안 및 개발 반영',
          ],
        },
        {
          projectName: 'PNS 그룹웨어 구축 참여 및 유지보수',
          projectDetail: [
            'Development Project Management',
            '일반적인 사이트 유지보수 및 비즈니스 로직 변경, 기능 추가',
            '레거시 코드 최소화(정리) 및 TDD 도입',
          ],
        },
        {
          projectName: '삼성전자 조직도 배치 모듈 개발',
          projectDetail: [
            '백엔드 Batch 서비스 개발',
            '그룹 조직도/직원 정보 변경 시 자동 사내 메신저 시스템 반영 인터페이스 개발',
          ],
        },
        {
          projectName: '한국 과학기술 연구원(KISTEP) 그룹웨어 개발',
          projectDetail: [
            '그룹웨어 요청 사항 프로젝트 일정 관리 및 서비스 개선 개발',
            '데이터 구성 컴포넌트 별 세부 정보 입력 및 규칙 정의 기능 개발',
            'Linux와 Nginx 활용 리버스 프록시 설정 및 서버 구축',
          ],
        },
        {
          projectName: '인천 교통 정보센터 실시간 버스노선(BIS) 웹 개선 사업',
          projectDetail: [
            '인천 시내 버스 위치 모니터링 화면 개발',
            'Flash ActionScript 활용 실시간 버스 위치 마킹 화면 개발',
            '교통 관제 실시간 API 호출 활용 서비스 동기화 백엔드 개발',
          ],
        },
        {
          projectName: '정보화 마을 데이터 아키텍처 분석 설계 작업',
          projectDetail: [
            '행정안전부 정보화 마을 인빌 시스템 데이터 통합/분산 체계화 및 데이터 모델링 작업',
          ],
        },
        {
          projectName: '법제처 고도화 프로젝트 TA(CI/CD) 환경 구축',
          projectDetail: [
            'Build Automation 툴 기반 테스트/스테이징/프로덕션 빌드 배포 시스템 구축',
          ],
        },
      ],
      skillKeywords: [
        'Java',
        'Spring',
        'Cordova',
        'Javascript',
        'Oracle11',
        'ActionScript',
        'ExtJS',
        'RabbitMQ',
        'DA#',
        'Erwin',
        'Cubrid',
        'Jenkins',
        'Linux',
        'Apache',
      ],
    },
    {
      title: 'Happy오후 3시',
      position: '대리(프리랜서, 비상근) - 운영관리팀',
      startedAt: '2009-02',
      endedAt: '2012-12',
      descriptions: [
        {
          projectName: 'JSP 및 PHP 기반 웹 서비스 개발 및 유지 보수 업무',
          projectDetail: [
            '서울시 장애인 협회 사이트 구축 및 운영 담당',
            'PHP, Wordpress 기반 쇼핑몰 운영 및 기능 추가',
            'JSP, Servlet 기반 다수 사이트 운영 및 기능 추가',
            'Linux와 Apache 등 활용 서버 인프라 구축',
          ],
        },
      ],
      skillKeywords: ['PHP', 'JSP', 'MySQL', 'Oracle9i', 'HTML5', ' Javascript', 'Linux', 'Apache'],
    },
    {
      title: '(주)하이미디어아카데미',
      position: '강사(프리랜서)',
      startedAt: '2008-03',
      endedAt: '2012-02',
      descriptions: [
        {
          projectName: 'IT 관련 교육강의 및 기타 업무',
          projectDetail: [
            'NCS 기반 IT 과정 커리큘럼 발굴 업무',
            'NCS 및 정규 교육 과정 강의(OA, 웹 프로그래밍, Flash 등)',
            '하이미디어(신촌, 노원), 더조은 아카데미(수원) 등 강의',
            '<b>주중 저녁 및 주말 수업 강의</b>',
          ],
        },
      ],
      skillKeywords: ['OA', 'Flash', 'ActionScript', 'HTML5', 'NCS'],
    },
  ],
};

export default experience;
